-- Highlight, edit, and navigate code

return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs", -- Sets main module to use for opts
    opts = {
        ensure_installed = {
            "bash",
            "bibtex",
            "blade",
            "c",
            "css",
            "gitignore",
            "html",
            "htmldjango",
            "hyprlang",
            "java",
            "javascript",
            "jsdoc",
            "json",
            "jsonc",
            "lua",
            "luadoc",
            "markdown",
            "markdown_inline",
            "norg",
            "php",
            "phpdoc",
            "printf",
            "python",
            "query",
            "regex",
            "scss",
            "svelte",
            "toml",
            "typescript",
            "typst",
            "vim",
            "vimdoc",
            "yaml",
        },
        auto_install = true,
        highlight = {
            enable = true,
            disable = { "latex" },
            additional_vim_regex_highlighting = { "ruby" },
        },
        indent = { enable = true, disable = { "ruby" } },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = "<C-m>",
                node_incremental = "<C-m>",
                scope_incremental = false,
                node_decremental = "<Backspace>",
            },
        },
    },
}
